### ISSUE TITLE
Witch ticking issue

### ISSUE THREAD

**Issue by idh1120** [CrimsonCrips/AlexsMobsInteraction#15]
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.goal.target.NearestHealableRaiderTargetGoal.m_26094_()" because "this.healRaidersGoal" is null
	at net.minecraft.world.entity.monster.Witch.m_8107_(Witch.java:583) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:alexsmobsinteraction.mixins.json:mobs.AMIWitch from mod alexsmobsinteraction,pl:mixin:APP:dawnera.mixins.json:entity.MixinWitch from mod dawnera,pl:mixin:APP:forge-dramaticdoors_forge.mixins.json:WitchMixin from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:connectormod:insertInjectionTarget,xf:fml:connectormod:updateItemUseStartTreshold,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:connectormod:insertInjectionTarget,xf:fml:connectormod:updateItemUseStartTreshold,pl:mixin:APP:forge-badoptimizations.mixins.json:entitydata.MixinLivingEntity from mod (unknown),pl:mixin:APP:citadel.mixins.json:LivingEntityMixin from mod citadel,pl:mixin:APP:etched.mixins.json:client.ClientLivingEntityMixin from mod etched,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_cap_retrieval.LivingEntityMixin from mod modernfix,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin from mod supplementaries,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin from mod supplementaries,pl:mixin:APP:curios.mixins.json:MixinLivingEntity from mod curios,pl:mixin:APP:fabric-entity-events-v1.mixins.json:LivingEntityMixin from mod fabric_entity_events_v1,pl:mixin:APP:fabric-entity-events-v1.mixins.json:elytra.LivingEntityMixin from mod fabric_entity_events_v1,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity from mod caelus,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin from mod upgrade_aquatic,pl:mixin:APP:status-effect-bars.mixins.json:LivingEntityMixin from mod status_effect_bars,pl:mixin:APP:neapolitan.mixins.json:LivingEntityMixin from mod neapolitan,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor from mod bettercombat,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin from mod bettercombat,pl:mixin:APP:notenoughanimations.mixins.json:LivingEntityMixin from mod notenoughanimations,pl:mixin:APP:crittersandcompanions.mixins.json:LivingEntityMixin from mod crittersandcompanions,pl:mixin:APP:canary.mixins.json:alloc.enum_values.living_entity.LivingEntityMixin from mod canary,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin from mod canary,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin from mod canary,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin from mod canary,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin from mod canary,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin from mod canary,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.dismount_dead_entities.MixinLivingEntity from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.ladders.MixinLivingEntity from mod valkyrienskies,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin from mod domesticationinnovation,pl:mixin:APP:adastra-common.mixins.json:common.EntityBelowWorldMixin from mod ad_astra,pl:mixin:APP:adastra-common.mixins.json:common.LivingEntityAccessor from mod ad_astra,pl:mixin:APP:adastra-common.mixins.json:common.LivingEntityMixin from mod ad_astra,pl:mixin:APP:adastra-common.mixins.json:common.radio.LivingEntityMixin from mod ad_astra,pl:mixin:APP:galosphere.mixins.json:LivingEntityMixin from mod galosphere,pl:mixin:APP:insanelib.mixins.json:LivingEntityMixin from mod insanelib,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity from mod bookshelf,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity from mod bookshelf,pl:mixin:APP:dummmmmmy-common.mixins.json:LivingEntityMixin from mod dummmmmmy,pl:mixin:APP:snifferplus.mixins.json:MixinLivingEntity from mod snifferplus,pl:mixin:APP:cataclysm.mixins.json:LivingEntityMixin from mod cataclysm,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:LivingEntityMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:mixins.artifacts.common.json:accessors.LivingEntityAccessor from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:item.hurtsound.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.chorustotem.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:item.hurtsound.client.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.pocketpiston.client.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.forge.json:item.wearable.snowshoes.LivingEntityMixin from mod artifacts,pl:mixin:APP:particular.mixins.json:InvokerLivingEntity from mod particular,pl:mixin:APP:alexscaves.mixins.json:LivingEntityMixin from mod alexscaves,pl:mixin:APP:endermanoverhaul-common.mixins.json:common.LivingEntityMixin from mod endermanoverhaul,pl:mixin:APP:mixins.irons_spellbooks.json:LivingEntityMixin from mod irons_spellbooks,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin from mod expandability,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin from mod expandability,pl:mixin:APP:presencefootsteps.mixin.json:ILivingEntity from mod presencefootsteps,pl:mixin:APP:presencefootsteps.mixin.json:MLivingEntity from mod presencefootsteps,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin from mod create,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin from mod create,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor from mod create,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin from mod obscure_api,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:fabric-entity-events-v1.mixins.json:MobEntityMixin from mod fabric_entity_events_v1,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.MobMixin from mod canary,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.MobMixin from mod canary,pl:mixin:APP:domesticationinnovation.mixins.json:MobMixin from mod domesticationinnovation,pl:mixin:APP:adastra-common.mixins.json:common.MobMixin from mod ad_astra,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob from mod bookshelf,pl:mixin:APP:caverns_and_chasms.mixins.json:MobMixin from mod caverns_and_chasms,pl:mixin:APP:mixins.letmedespawn.json:MobMixin from mod letmedespawn,pl:mixin:APP:buzzier_bees.mixins.json:MobEntityMixin from mod buzzier_bees,pl:mixin:APP:mixins.artifacts.common.json:accessors.MobAccessor from mod artifacts,pl:mixin:APP:alexscaves.mixins.json:MobMixin from mod alexscaves,pl:mixin:APP:moonlight-common.mixins.json:EntityMixin from mod moonlight,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin from mod modernfix,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin from mod snowrealmagic,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin from mod supplementaries,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel from mod sereneseasons,pl:mixin:APP:ksyxis.mixins.json:ServerLevelMixin from mod ksyxis,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:chunk.replace_streams.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:util.accessors.ServerLevelAccessor from mod canary,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.ServerLevelMixin from mod canary,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate from mod cold_sweat,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinServerLevel from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinServerLevel from mod valkyrienskies,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin from mod ad_astra,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin from mod ad_astra,pl:mixin:APP:ritchiesprojectilelib.mixins.json:ServerLevelMixin from mod ritchiesprojectilelib,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:caverns_and_chasms.mixins.json:ServerLevelMixin from mod caverns_and_chasms,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin from mod blueprint,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor from mod create,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:citadel.mixins.json:LevelMixin from mod citadel,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin from mod sliceanddice,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel from mod sereneseasons,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.LevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:util.block_entity_retrieval.LevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin from mod canary,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.clip_replace.MixinLevel from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.get_entities.MixinLevel from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.world_border.MixinLevel from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:world.level.MixinLevel from mod valkyrienskies,pl:mixin:APP:adastra.mixins.json:common.multipart.LevelMixin from mod ad_astra,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:AttachmentTargetsMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:WorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:lucent.mixins.json:LevelMixin from mod lucent,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin from mod modernfix,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin from mod snowrealmagic,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin from mod supplementaries,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel from mod sereneseasons,pl:mixin:APP:ksyxis.mixins.json:ServerLevelMixin from mod ksyxis,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:chunk.replace_streams.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:util.accessors.ServerLevelAccessor from mod canary,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.ServerLevelMixin from mod canary,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate from mod cold_sweat,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinServerLevel from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinServerLevel from mod valkyrienskies,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin from mod ad_astra,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin from mod ad_astra,pl:mixin:APP:ritchiesprojectilelib.mixins.json:ServerLevelMixin from mod ritchiesprojectilelib,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:caverns_and_chasms.mixins.json:ServerLevelMixin from mod caverns_and_chasms,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin from mod blueprint,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor from mod create,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:canary.mixins.json:collections.entity_ticking.EntityTickListMixin from mod canary,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_serverlevel,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin from mod modernfix,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin from mod snowrealmagic,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin from mod supplementaries,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel from mod sereneseasons,pl:mixin:APP:ksyxis.mixins.json:ServerLevelMixin from mod ksyxis,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:chunk.replace_streams.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin from mod canary,pl:mixin:APP:canary.mixins.json:util.accessors.ServerLevelAccessor from mod canary,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.ServerLevelMixin from mod canary,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate from mod cold_sweat,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinServerLevel from mod valkyrienskies,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinServerLevel from mod valkyrienskies,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin from mod ad_astra,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin from mod ad_astra,pl:mixin:APP:ritchiesprojectilelib.mixins.json:ServerLevelMixin from mod ritchiesprojectilelib,pl:mixin:APP:fabric-data-attachment-api-v1.mixins.json:ServerWorldMixin from mod fabric_data_attachment_api_v1,pl:mixin:APP:caverns_and_chasms.mixins.json:ServerLevelMixin from mod caverns_and_chasms,pl:mixin:APP:fabric-api-lookup-api-v1.mixins.json:ServerWorldMixin from mod fabric_api_lookup_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:ServerWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin from mod blueprint,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor from mod create,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:create_interactive-common.mixins.json:MixinMinecraftServer from mod create_interactive,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin from mod ksyxis,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer from mod valkyrienskies,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:mixins.letmedespawn.json:MinecraftServerMixin from mod letmedespawn,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:create_interactive-common.mixins.json:MixinMinecraftServer from mod create_interactive,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin from mod ksyxis,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer from mod valkyrienskies,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:mixins.letmedespawn.json:MinecraftServerMixin from mod letmedespawn,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin from mod modernfix,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:create_interactive-common.mixins.json:MixinMinecraftServer from mod create_interactive,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin from mod ksyxis,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer from mod valkyrienskies,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:mixins.letmedespawn.json:MinecraftServerMixin from mod letmedespawn,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23639!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:create_interactive-common.mixins.json:MixinMinecraftServer from mod create_interactive,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin from mod modernfix,pl:mixin:APP:ksyxis.mixins.json:MinecraftServerMixin from mod ksyxis,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer from mod valkyrienskies,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:mixins.letmedespawn.json:MinecraftServerMixin from mod letmedespawn,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Alexs Mobs Interaction (alexsmobsinteraction), Version: 3.0
		Issue tracker URL: https://github.com/CrimsonCrips/AlexsInteractionAddon/issues
		Mixin class: com.crimsoncrips.alexsmobsinteraction.mixins.mobs.AMIWitch
		Target: net.minecraft.world.entity.monster.Witch
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.monster.Witch.m_8107_(Witch.java:583)

**Comment by CrimsonCrips** [comment]
Fixed
