### ISSUE TITLE
The console has the following warning, but it did not cause a crash

### ISSUE THREAD

**Issue by ASHISK404** [CrimsonCrips/AlexsMobsInteraction#21]
1.20.1,alexsmobsinteraction-3.1, mohist server

[15:34:33 WARN]: Exception loading entity: 
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "this.f_25994_" is null
        at net.minecraft.world.entity.ai.goal.WrappedGoal.hashCode(WrappedGoal.java:103) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at java.util.HashMap.hash(HashMap.java:338) ~[?:?]
        at java.util.HashMap.put(HashMap.java:610) ~[?:?]
        at java.util.HashSet.add(HashSet.java:221) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.m_25352_(GoalSelector.java:48) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at com.github.alexthe666.alexsmobs.entity.EntitySoulVulture.handler$zeo000$alexsmobsinteraction$SoulVultureGoals(EntitySoulVulture.java:541) ~[alexsmobs-1.22.8.jar%23367!/:1.22.8]
        at com.github.alexthe666.alexsmobs.entity.EntitySoulVulture.m_8099_(EntitySoulVulture.java) ~[alexsmobs-1.22.8.jar%23367!/:1.22.8]
        at net.minecraft.world.entity.Mob.<init>(Mob.java:145) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.world.entity.PathfinderMob.<init>(PathfinderMob.java:15) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.world.entity.monster.Monster.<init>(Monster.java:31) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at com.github.alexthe666.alexsmobs.entity.EntitySoulVulture.<init>(EntitySoulVulture.java:70) ~[alexsmobs-1.22.8.jar%23367!/:1.22.8]
        at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:553) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.world.entity.EntityType.m_185996_(EntityType.java:558) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraft.world.entity.EntityType.m_20642_(EntityType.java:557) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.world.entity.EntityType.m_20669_(EntityType.java:635) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.world.entity.EntityType.m_20645_(EntityType.java:591) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.world.entity.EntityType$1.m_147056_(EntityType.java:612) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
        at net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:611) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.minecraft.world.level.chunk.storage.EntityStorage.m_223456_(EntityStorage.java:53) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1029) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1012) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1006) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:992) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:908) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23514!/:?]
        at java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by CrimsonCrips** [comment]
This issue caused Soul Vultures to not spawn or can be spawned

this will be fixed in the upcoming 3.3 update
